import Head from 'next/head'
import ContentJwVideo from '../../components/JwVideo'
import { getMediaID, getVideoData } from '@/getData';

//Update this to update the video

export async function getServerSideProps() {
  const res = await fetch(`https://cdn.jwplayer.com/v2/media/${getMediaID()}`).catch(err => console.log('Please check mediaID'));
  const {playlist} = await res?.json();

  let fileSource; 
  const fileResolution = ['1080p', '720p', '540p', '360p', '270p', '180p']

  for (const resolution of fileResolution) {
    fileSource = playlist[0].sources.find((source: any) => source.label === resolution && source.type.includes('video'));
    if (fileSource) {
      break;
    }
  }

  return {
   props: {
    data: playlist || null,
    file: fileSource?.file
   }
  }
}


export default function Home({data, file}:{data: any, file:string}) {
  if(data){
    const videoData = getVideoData(data, file)
    return (
      <>
        <Head>
          <title>JW Performance testing</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div style={{height: '100%', width: '620px'}}>
          <ContentJwVideo data={videoData} type={''} meta={''} descendants={''} /> 
        </div>      
      </>
    )
  }
  
}
